name: Update Semver

on:
  workflow_call:

jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: tag_version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}-build${increment}"
          bump_each_commit: true
          version_from_branch: true
          debug: true

      - name: Increment Tag and Push
        run: |
          base_tag=${{ steps.tag_version.outputs.version_tag }}
          max_attempts=10
          attempt=1
          tag_to_push=$base_tag

          while [ $attempt -le $max_attempts ]; do
            if git rev-parse "$tag_to_push" >/dev/null 2>&1; then
              echo "Tag $tag_to_push already exists. Incrementing version..."
              # Extract base version and safely initialize build_number
              if [[ "$tag_to_push" =~ -build([0-9]+)$ ]]; then
                build_number="${BASH_REMATCH[1]}"
              else
                build_number=0
              fi

              version_base=$(echo "$tag_to_push" | sed -E 's/^(v[0-9]+\.[0-9]+\.[0-9]+)(-build[0-9]*)?$/\1/')
              build_number=$((build_number + 1))
              tag_to_push="${version_base}-build${build_number}"
              attempt=$((attempt + 1))
            else
              echo "Tag $tag_to_push does not exist. Creating and pushing..."
              git tag "$tag_to_push"
              git push origin "$tag_to_push"
              break
            fi
          done

          if [ $attempt -gt $max_attempts ]; then
            echo "Failed to create a unique tag after $max_attempts attempts."
            exit 1
          fi

      - name: Show Generated Tag
        run: |
          tag_v=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Last git tag: $tag_v"
